# Copyright 2018-2018 adorsys GmbH & Co KG
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
server:
  port: 8093

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: ledgers
  resource: ledgers-client
  public-client: false
  principal-attribute: preferred_username
  credentials:
    secret: a61a81cd-7178-40d8-8386-ed02791e6592 #Here should be personal generated secret for client (swap public to 'private?' generate secret, swap to public again)

spring:
  liquibase:
    enabled: true
    change-log: classpath:liquibase-master-changelog.xml
    default-schema: tpp
  jpa:
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 2MB
      max-request-size: 2MB
  jackson:
    serialization:
      write_dates_as_timestamps: false
  devtools:
    remote:
      secret: fractal
      #DBs Properties
spring.datasource.hikari.jdbc-url: jdbc:postgresql://localhost:5432/consent?currentSchema=consent
spring.datasource.hikari.username: cms
spring.datasource.hikari.password: cms

spring.tpp.datasource.hikari.jdbc-url: jdbc:postgresql://localhost:5432/consent?currentSchema=tpp
spring.tpp.datasource.hikari.username: cms
spring.tpp.datasource.hikari.password: cms

ledgers.url: http://localhost:8088

license.url: https://github.com/adorsys/xs2a/blob/master/LICENSE.md

feign:
  client:
    config:
      default:
        loggerLevel: full

logging.level.de.adorsys.psd2.sandbox.tpp: INFO

logging.level.de.adorsys.ledgers.middleware.client.rest.AdminRestClient: DEBUG

# Cors configuration
management:
  endpoints:
    web:
      cors:
        allow-credentials: true
        allowed-origins: "*"
        allowed-headers: "*"
        allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
        max-age: 3600
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  health:
    mail:
      enabled: false

app:
  endpoints:
    tpp.self.registration.disabled: false
