#
# Copyright 2018-2024 adorsys GmbH & Co KG
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version. This program is distributed in the hope that
# it will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.
#
# This project is also available under a separate commercial license. You can
# contact us at sales@adorsys.com.
#

server:
  # Authorization HTTP header requires to enlarge max header size.
  max-http-header-size: 65000
  port: 8090
  servlet:
    session:
      cookie:
        secure: false
        max-age: 300
        http-only: true
        path: /

keycloak:
  auth-server-url: http://localhost:8080
  realm: ledgers
  resource: ledgers-client
  public-client: false
  principal-attribute: preferred_username
  credentials:
    secret: a61a81cd-7178-40d8-8386-ed02791e6592 #Here should be personal generated secret for client (swap public to 'private?' generate secret, swap to public again)

db:
  host: localhost
  database: consent
  user: cms
  password: cms
  port: 5432
  url: jdbc:postgresql://${db.host}:${db.port}/${db.database}

cms:
  datasource:
    jdbc-url: ${db.url}?currentSchema=consent
    username: ${db.user}
    password: ${db.password}

spring:
  application.name: ledgers-xs2a-oba
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: consent
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
  jackson:
    serialization:
      write_dates_as_timestamps: false

ledgers.url: http://localhost:8088
xs2a.url: http://localhost:8089
cms.url: http://localhost:38080
oba.url: http://localhost:4400
self.url: http://localhost:8090

oba.maxLoginFailedCount: 3

license.url: https://www.gnu.org/licenses/agpl-3.0.html

skip.ssl.certificate.verification: true

# For now this must be the same as the property configured in
# user-service.jwt.hs256.secret from /ledgers-app/src/main/resources/application.yml
online-banking.sca:
  jwt.hs256.secret: 6VFX8YFQG5DLFKZIMNLGH9P406XR1SY4

feign:
  okhttp:
    enabled: true
  client:
    config:
      default:
        loggerLevel: full

logging.level.de.adorsys.ledgers.middleware: DEBUG
logging.level.org.adorsys.ledgers.consent: DEBUG
logging.level.de.adorsys.ledgers.xs2a.api: DEBUG
logging.level.de.adorsys.ledgers.rest: DEBUG
logging.level.de.adorsys.psd2.consent: DEBUG
logging.level.org.hibernate: INFO
logging.level.com.netflix.config: INFO
logging.level.com.zaxxer.hikari: INFO

# Cors configuration
management:
  endpoints:
    web:
      cors:
        allow-credentials: true
        allowed-origin-patterns: "*"
        allowed-headers: "*"
        allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
        max-age: 3600
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  health:
    mail:
      enabled: false
