name: Develop CI

on:
  push:
    branches:
      - develop

env:
  SONAR_PRJ_KEY: adorsys_XS2A-Sandbox
  SONAR_ORG: adorsys
  SONAR_HOST: https://sonarcloud.io
  GPG_EXECUTABLE: ${{ secrets.GPG_EXECUTABLE }}
  GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY}}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

jobs:
  build_and_test:
    name: Build and test Modelbank (openjdk 1.11)
    runs-on: ubuntu-latest
    steps:
      - name: Clone Modelbank repository
        uses: actions/checkout@v2

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          architecture: x64

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build Modelbank
        run: mvn -ntp -DskipTests -DskipITs -Dmaven.javadoc.skip=true clean install

      - name: Run Unit Tests
        run: mvn -ntp -DskipITs --fail-at-end clean install

  sonar:
    name: Publish code coverage to Sonar Cloud
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Clone Modelbank develop repository
        uses: actions/checkout@v2

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          architecture: x64

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Publish to sonarcloud
        run: >
          mvn
          -ntp
          clean
          org.jacoco:jacoco-maven-plugin:prepare-agent
          install
          sonar:sonar
          -Pcoverage
          -Dsonar.host.url=${{ env.SONAR_HOST }}
          -Dsonar.projectKey=${{ env.SONAR_PRJ_KEY }}
          -Dsonar.organization=${{ env.SONAR_ORG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deployMavenCentral:
    name: Publish Modelbank artifacts to Maven Central
    needs: [build_and_test, sonar]
    runs-on: ubuntu-latest
    steps:
      - name: Clone Modelbank repository
        uses: actions/checkout@v2

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          architecture: x64

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Publish to Maven Central
        run: |
          gpg --version
          export GPG_TTY="$( tty )" #need to run to sign artifacts with maven
          echo ${{ secrets.GPG_SECRET_KEY }} | base64 --decode | gpg --import --batch
          echo ${{ secrets.GPG_OWNERTRUST }} | base64 --decode | gpg --batch --import-ownertrust
          mvn -ntp --settings scripts/mvn-release-settings.xml -Prelease -DskipTests -U deploy
